import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'
import './globals.css'
import { Ubuntu } from 'next/font/google'
import { store } from './redux/store'
import { Providers } from './redux/provider'

const ubuntu = Ubuntu({ subsets: ['latin'], weight: ['300', '400', '500', '700'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
        <Providers>
		<html lang='en'>
			<body className={`p-4 ${ubuntu.className}`}>
				<Header />
				{children}
        <Footer/>
			</body>
		</html>
        </Providers>
	)
}
